"""ComfortSense algorithm — Python model stub.

Stub generated by /toolchain scaffold. NOT regenerated on subsequent
scaffold runs once you implement the body (detection: absence of
NotImplementedError).

This Python model must mirror the firmware algorithm. The signal-only
simulation path uses run() directly; the Renode path flashes the C++
implementation. Both paths must agree at the Stage 1 gate (parity check).

Article I — every constant inside run() must trace to a domain primitive
named in Amendment 1 via an inline comment. Constants without a primitive
citation are guesses and will be flagged by code-reviewer / police.

Amendment 1 — Domain Primitives:
    Filter delta-P (Pa)         — pressure drop across the HVAC filter.
                                  Alert window: ratio in [1.8, 1.9] of
                                  per-deployment baseline delta-P0.
                                  Inferred from IMU + microphone + CT.
    HVAC operating regime       — categorical {off, heating, cooling}.
                                  Conditioning variable for the delta-P
                                  inference. Measured via outside thermometer.
"""
from __future__ import annotations

from typing import Any

import numpy as np


def run(samples: np.ndarray) -> dict[str, Any]:
    """Run the ComfortSense algorithm against synthetic or captured samples.

    Parameters
    ----------
    samples : np.ndarray of shape (n_steps, C)
        Sensor data in physical units. Column order matches
        src.events.ReadingEvent (ax_g, ay_g, az_g, gx_dps, gy_dps, gz_dps).

    Returns
    -------
    dict[str, Any]
        Keys correspond to Amendment 1 domain primitives:
          "filter_dp_ratio"      : float
              Estimated Filter delta-P expressed as ratio delta-P / delta-P0.
              Expected range: ~[1.0, 2.5]. Alert at >= 1.8 (Amendment 1).
          "filter_dp_pa"         : float | None
              Absolute Pa value if delta-P0 calibration is available, else None.
          "hvac_regime"          : str
              One of "off", "heating", "cooling".
          "alert"                : bool
              True iff filter_dp_ratio >= 1.8 (Amendment 1 alert window low edge).
          "diagnostics"          : dict[str, float]
              Free-form intermediate metrics (rms_g, dominant_freq_hz, etc.).
              Used by /plot for Article I evidence; not part of the contract.
    """
    raise NotImplementedError(
        "implement Filter delta-P inference from IMU + microphone + CT, "
        "regime-conditioned via outside_temp; mirror firmware logic in "
        "firmware/<stage>/<stage>.ino once written"
    )
