"""ComfortSense UART log parser — project-specific instance.

Generated by /toolchain scaffold — re-run to update.
Source: docs/toolchain_config.md ## Firmware UART Format

Public API:
    PARSER         — singleton UartParser configured for ComfortSense firmware
    parse_line(s)  — parse one UART line  -> UartEvent | SessionEndEvent | None
    parse_log(s)   — parse a multi-line log -> (events, session_ends)
"""
from __future__ import annotations

from crucible.signal.analysis import EventDefinition, UartParser
from crucible.signal.events import SessionEndEvent, UartEvent

READING_DEF = EventDefinition(
    name="reading",
    pattern=(
        r"READING ts=(\d+) "
        r"ax=(-?[\d.]+) ay=(-?[\d.]+) az=(-?[\d.]+) "
        r"gx=(-?[\d.]+) gy=(-?[\d.]+) gz=(-?[\d.]+)"
    ),
    fields=["ts_ms", "ax_g", "ay_g", "az_g", "gx_dps", "gy_dps", "gz_dps"],
    converters=[int, float, float, float, float, float, float],
)

METRIC_DEF = EventDefinition(
    name="metric",
    pattern=r"METRIC ts=(\d+) rms_g=(-?[\d.]+) n=(\d+)",
    fields=["ts_ms", "rms_g", "n"],
    converters=[int, float, int],
)

ALERT_DEF = EventDefinition(
    name="alert",
    pattern=r"ALERT ts=(\d+) dp=(-?[\d.]+) regime=(\w+) alert=([01])",
    fields=["ts_ms", "dp_ratio", "regime", "alert"],
    converters=[int, float, str, lambda x: bool(int(x))],
)

PARSER = UartParser(
    event_definitions=[READING_DEF, METRIC_DEF, ALERT_DEF],
    session_end_marker="SESSION_END",
)


def parse_line(line: str) -> UartEvent | SessionEndEvent | None:
    return PARSER.parse_line(line)


def parse_log(text: str) -> tuple[list[UartEvent], list[SessionEndEvent]]:
    return PARSER.parse_log(text)
