"""ComfortSense UART event dataclasses.

Generated by /toolchain scaffold — re-run to update.
Source: docs/toolchain_config.md ## Firmware UART Format
        docs/device_context.md ## Signal Inventory

Re-scaffolding overwrites this file. Per Amendment 11 (Scaffold Immutability,
PROPOSED), regeneration after Stage 1 gate requires a Bill recording what
changed in the Signal Inventory or UART format and why.
"""
from __future__ import annotations

from dataclasses import dataclass

from crucible.signal.events import SessionEndEvent  # noqa: F401  (re-exported)


@dataclass
class ReadingEvent:
    """Raw IMU sample emitted at 1 Hz by stage0_sensor.ino.

    Fields trace to Signal Inventory rows:
      ax_g, ay_g, az_g  -> imu_accel_{x,y,z}  (g,    P1 Filter delta-P chain)
      gx_dps, gy_dps, gz_dps -> imu_gyro_{x,y,z} (deg/s, P1 Filter delta-P chain)
    """
    ts_ms: int
    ax_g: float
    ay_g: float
    az_g: float
    gx_dps: float
    gy_dps: float
    gz_dps: float


@dataclass
class AlertEvent:
    """Stage 1 algorithm output per 1660-sample decision window (~1 Hz).

    Emitted by stage1_algo_usb.ino (Bill 4, Case 7).
    UART format: ALERT ts=<ms> dp=<float> regime=<str> alert=<0|1>

      ts_ms    -> firmware millis() at emission
      dp_ratio -> filter_dp_ratio: ΔP/ΔP₀ vibration-proxy estimate (P1)
      regime   -> hvac_regime: "cooling" default for IMU-only Renode path
      alert    -> True iff dp_ratio >= 1.8 (Amendment 1 P1 alert window low edge)
    """
    ts_ms: int
    dp_ratio: float
    regime: str
    alert: bool


@dataclass
class MetricEvent:
    """Algorithm output emitted at 2 Hz by stage0_algo_{usb,ble}.ino.

    Stage 0 liveness only: rms_g is sqrt(mean(ax^2 + ay^2 + az^2)) over a
    500 ms sliding window. No Filter delta-P threshold is applied — that
    is Stage 1+ work and must be Bill-governed (Article I, Amendment 1).

      ts_ms  -> firmware millis() at emission time
      rms_g  -> derived scalar (g) — proxy for vibration energy, P1 chain
      n      -> samples in the window (50 once warmed, fewer during prime)
    """
    ts_ms: int
    rms_g: float
    n: int
