"""ComfortSense plot wrappers — domain-named convenience functions.

Generated by /toolchain scaffold — re-run to update.
Source: docs/governance/amendments.md Amendment 1 (Domain Primitives)
        docs/device_context.md Signal Inventory

Each wrapper fills the generic crucible.signal.plot functions with the
labels, units, and (where defined) thresholds from Amendment 1.

Threshold note (Amendment 1):
  The Filter delta-P alert window is 1.8 * delta-P0 to 1.9 * delta-P0,
  where delta-P0 is the per-deployment installed-new baseline. There is
  NO absolute Pa threshold defined at scaffold time — callers must pass
  the calibrated baseline at runtime. The wrappers therefore expose
  threshold_ratio (default 1.85) and dp0_pa as parameters.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence

from crucible.signal.plot import (
    plot_metric_bar,
    plot_metric_timeline,
    plot_sensor_trace,
)

# Channel layout for the IMU 6-axis trace plots — matches src/events.py field order
# and the Signal Inventory rows imu_accel_{x,y,z} / imu_gyro_{x,y,z}.
IMU_CHANNELS = ("ax", "ay", "az", "gx", "gy", "gz")
IMU_GROUPS = (("Accel", "g"), ("Gyro", "deg/s"))


def plot_imu_trace(
    samples,
    odr_hz: float = 100.0,
    title: str = "ComfortSense IMU Trace (P1 — Filter delta-P chain)",
    output: str | Path = "imu_trace.png",
) -> Path:
    """Plot 6-axis IMU samples as time-series traces (accel + gyro subplots).

    samples : np.ndarray (N, 6)  columns ordered ax, ay, az, gx, gy, gz.
    """
    return plot_sensor_trace(
        samples=samples,
        odr_hz=odr_hz,
        title=title,
        output=output,
        channels=IMU_CHANNELS,
        channel_groups=IMU_GROUPS,
    )


def plot_filter_dp_comparison(
    results: dict[str, dict],
    metric_key: str = "estimated_dp_ratio",
    dp0_pa: float | None = None,
    threshold_ratio: float = 1.85,
    output: str | Path = "filter_dp_comparison.png",
    labels: Sequence[str] | None = None,
    compare_key: str | None = None,
    compare_label: str = "Reference delta-P",
) -> Path:
    """Bar chart comparing estimated Filter delta-P across simulation profiles.

    Amendment 1 alert window: ratio in [1.8, 1.9] of delta-P0.
    threshold_ratio defaults to the midpoint 1.85.

    If dp0_pa is provided the y-axis is plotted in absolute Pa
    (metric values are multiplied by dp0_pa before plotting); otherwise
    the y-axis is the dimensionless ratio delta-P / delta-P0.
    """
    if dp0_pa is not None:
        scaled = {
            k: {**v, metric_key: float(v.get(metric_key, 0.0)) * dp0_pa}
            for k, v in results.items()
        }
        if compare_key is not None:
            for k in scaled:
                if compare_key in results[k]:
                    scaled[k][compare_key] = (
                        float(results[k][compare_key]) * dp0_pa
                    )
        return plot_metric_bar(
            results=scaled,
            metric_key=metric_key,
            metric_label="Filter delta-P",
            metric_unit="Pa",
            threshold=threshold_ratio * dp0_pa,
            threshold_label=f"alert ({threshold_ratio} x delta-P0 = "
                            f"{threshold_ratio * dp0_pa:.1f} Pa)",
            labels=labels,
            compare_key=compare_key,
            compare_label=compare_label,
            output=output,
            title="ComfortSense Filter delta-P (P1)",
        )

    return plot_metric_bar(
        results=results,
        metric_key=metric_key,
        metric_label="Filter delta-P / delta-P0",
        metric_unit="ratio",
        threshold=threshold_ratio,
        threshold_label=f"alert ({threshold_ratio} x delta-P0)",
        labels=labels,
        compare_key=compare_key,
        compare_label=compare_label,
        output=output,
        title="ComfortSense Filter delta-P (P1, ratio)",
    )


def plot_filter_dp_timeline(
    events: list,
    index_field: str = "ts_ms",
    primary_field: str = "estimated_dp_ratio",
    secondary_field: str | None = "rms_g",
    threshold_ratio: float = 1.85,
    output: str | Path = "filter_dp_timeline.png",
    title: str = "ComfortSense Filter delta-P Timeline (P1)",
) -> Path:
    """Plot Filter delta-P (and optionally a secondary signal) over time.

    Defaults assume the algorithm emits events with an estimated_dp_ratio
    field. For raw Stage 0 METRIC events use primary_field='rms_g' and
    threshold_ratio=None (no Article I threshold at Stage 0).
    """
    return plot_metric_timeline(
        events=events,
        index_field=index_field,
        primary_field=primary_field,
        primary_label="Filter delta-P / delta-P0",
        primary_unit="ratio",
        secondary_field=secondary_field,
        secondary_label="Accel RMS" if secondary_field == "rms_g" else secondary_field,
        secondary_unit="g" if secondary_field == "rms_g" else None,
        threshold=threshold_ratio,
        output=output,
        title=title,
    )


def plot_hvac_regime_timeline(
    events: list,
    index_field: str = "ts_ms",
    primary_field: str = "regime_code",
    output: str | Path = "hvac_regime_timeline.png",
    title: str = "ComfortSense HVAC Operating Regime (P2)",
) -> Path:
    """Plot HVAC regime classification over time.

    regime_code convention (project-defined, NOT a primitive value):
      0 = off, 1 = heating, 2 = cooling.
    The categorical primitive is plotted as an integer step trace —
    no threshold line (P2 has no scalar pass/fail criterion).
    """
    return plot_metric_timeline(
        events=events,
        index_field=index_field,
        primary_field=primary_field,
        primary_label="Regime (0=off, 1=heat, 2=cool)",
        primary_unit="code",
        threshold=None,
        output=output,
        title=title,
    )
