"""ComfortSense signal generator — physics model stub.

Stub generated by /toolchain scaffold. NOT regenerated on subsequent
scaffold runs once you implement the bodies (detection: absence of
NotImplementedError).

Implement generate(profile, n_steps) for each profile listed in the
Operating Envelope of docs/device_context.md. The signal-only simulation
path (fast, no firmware required) calls this directly; the Renode path
flashes firmware that consumes synthetic samples derived from the same
generator.

Return contract:
    np.ndarray of shape (n_steps, C) where C is the number of sensor
    channels parseable from one ReadingEvent (currently 6 for the IMU:
    ax_g, ay_g, az_g, gx_dps, gy_dps, gz_dps).

    Channel order MUST match the field order in src.events.ReadingEvent
    so that downstream analysis can map columns back to Signal Inventory
    rows without an explicit mapping table.

    Optional extra channels for microphone (dBSPL), outside_temp (deg C),
    and ct_current_rms (A RMS) may be appended later; if you do, update
    src.events.ReadingEvent and re-scaffold (Bill required, Amendment 11).

Profiles (from docs/device_context.md ## Device Purpose Operating Envelope):
    normal                      — typical Canadian rooftop, HVAC active
    worst_case_high_wind        — wind shake adds non-HVAC vibration
    worst_case_rapid_dust_load  — wildfire / dust storm rapid clog onset

If you need to split these by HVAC regime (heating vs cooling) or by filter
loading (clean / loaded / clog_alert), introduce sub-profiles via /spec or
a Bill — do not hard-code new profile names here without governance trace.
"""
from __future__ import annotations

import numpy as np


def generate(profile: str, n_steps: int) -> np.ndarray:
    """Generate synthetic IMU samples for a named profile.

    Parameters
    ----------
    profile : str
        One of: "normal", "worst_case_high_wind", "worst_case_rapid_dust_load".
    n_steps : int
        Number of samples to generate. Time axis is implicit (sample index);
        the caller knows the intended ODR (default 100 Hz, see firmware
        SAMPLE_PERIOD_MS in stage0_algo_*.ino).

    Returns
    -------
    np.ndarray of shape (n_steps, 6)
        Columns: ax_g, ay_g, az_g, gx_dps, gy_dps, gz_dps.
        Physical units must match Signal Inventory ranges:
          accel  +/- 2 g  (saturate, do not wrap)
          gyro   +/- 250 deg/s
    """
    if profile == "normal":
        raise NotImplementedError(
            "implement clean-filter HVAC vibration baseline (regime-conditioned)"
        )
    if profile == "worst_case_high_wind":
        raise NotImplementedError(
            "implement wind-shake disturbance overlaid on clean-filter baseline"
        )
    if profile == "worst_case_rapid_dust_load":
        raise NotImplementedError(
            "implement rapid Filter delta-P rise on hours timescale (wildfire/dust)"
        )
    raise ValueError(
        f"unknown profile {profile!r} — register new profiles in "
        "docs/device_context.md Operating Envelope (Bill required)"
    )
